repos:
  - repo: local
    hooks:
      - id: {{package_name}}-dev-check
        name: {{package_name}} dev check (ruff + format + mypy + pytest)
        entry: uv run dev check
        language: system
        pass_filenames: false
        stages: [pre-commit]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.30.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
