name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Run CI checks (ruff + format --check + mypy + build)
        run: uv run dev ci
